Fixed problem in SuiteDiscoveryHelper.scala. I wasn't checking to make sure the Suite was non-abstract in isAccessibleSuite. That was causing FunSuite1, which was abstract, to be attempted to be instantiated. Also, backed out a change in which I was catching NoClassDefFoundError. It was actually correct to not catch it. The error message was that "this is likely due to an error in your runpath", and that's how I fixed it. I added build onto the runpath. The wierd thing is why isn't FunSuite getting picked up from the parent loader?
git-svn-id: http://scalatest.googlecode.com/svn/trunk@29 fd1274fd-080f-5963-8033-43ee40fcd1de